INSERT INTO public.pais (id, nombre) VALUES 
  (nextval('seq_pais'), 'Afganistán'), 
  (nextval('seq_pais'), 'Albania'),
  (nextval('seq_pais'), 'Alemania'),
  (nextval('seq_pais'), 'Algeria'),
  (nextval('seq_pais'), 'Andorra'),
  (nextval('seq_pais'), 'Angola'),
  (nextval('seq_pais'), 'Anguilla'),
  (nextval('seq_pais'), 'Antigua y Barbuda'),
  (nextval('seq_pais'), 'Antillas Holandesas'),
  (nextval('seq_pais'), 'Arabia Saudita'),
  (nextval('seq_pais'), 'Argentina'),
  (nextval('seq_pais'), 'Armenia'),
  (nextval('seq_pais'), 'Aruba'),
  (nextval('seq_pais'), 'Australia'),
  (nextval('seq_pais'), 'Austria'),
  (nextval('seq_pais'), 'Azerbaiyán'),
  (nextval('seq_pais'), 'Bahamas'),
  (nextval('seq_pais'), 'Bahrein'),
  (nextval('seq_pais'), 'Bangladesh'),
  (nextval('seq_pais'), 'Barbados'),
  (nextval('seq_pais'), 'Bélgica'),
  (nextval('seq_pais'), 'Belice'),
  (nextval('seq_pais'), 'Benín'),
  (nextval('seq_pais'), 'Bermudas'),
  (nextval('seq_pais'), 'Bielorrusia'),
  (nextval('seq_pais'), 'Bolivia'),
  (nextval('seq_pais'), 'Bosnia y Herzegovina'),
  (nextval('seq_pais'), 'Botsuana'),
  (nextval('seq_pais'), 'Brasil'),
  (nextval('seq_pais'), 'Brunéi'),
  (nextval('seq_pais'), 'Bulgaria'),
  (nextval('seq_pais'), 'Burkina Faso'),
  (nextval('seq_pais'), 'Burundi'),
  (nextval('seq_pais'), 'Bután'),
  (nextval('seq_pais'), 'Cabo Verde'),
  (nextval('seq_pais'), 'Camboya'),
  (nextval('seq_pais'), 'Camerún'),
  (nextval('seq_pais'), 'Canadá'),
  (nextval('seq_pais'), 'Chad'),
  (nextval('seq_pais'), 'Chile'),
  (nextval('seq_pais'), 'China'),
  (nextval('seq_pais'), 'Chipre'),
  (nextval('seq_pais'), 'Colombia'),
  (nextval('seq_pais'), 'Comores'),
  (nextval('seq_pais'), 'Congo (Brazzaville)'),
  (nextval('seq_pais'), 'Congo (Kinshasa)'),
  (nextval('seq_pais'), 'Cook, Islas'),
  (nextval('seq_pais'), 'Corea del Norte'),
  (nextval('seq_pais'), 'Corea del Sur'),
  (nextval('seq_pais'), 'Costa de Marfil'),
  (nextval('seq_pais'), 'Costa Rica'),
  (nextval('seq_pais'), 'Croacia'),
  (nextval('seq_pais'), 'Cuba'),
  (nextval('seq_pais'), 'Dinamarca'),
  (nextval('seq_pais'), 'Djibouti, Yibuti'),
  (nextval('seq_pais'), 'Ecuador'),
  (nextval('seq_pais'), 'Egipto'),
  (nextval('seq_pais'), 'El Salvador'),
  (nextval('seq_pais'), 'Emiratos Árabes Unidos'),
  (nextval('seq_pais'), 'Eritrea'),
  (nextval('seq_pais'), 'Eslovaquia'),
  (nextval('seq_pais'), 'Eslovenia'),
  (nextval('seq_pais'), 'España'),
  (nextval('seq_pais'), 'Estados Unidos'),
  (nextval('seq_pais'), 'Estonia'),
  (nextval('seq_pais'), 'Etiopía'),
  (nextval('seq_pais'), 'Feroe, Islas'),
  (nextval('seq_pais'), 'Filipinas'),
  (nextval('seq_pais'), 'Finlandia'),
  (nextval('seq_pais'), 'Fiyi'),
  (nextval('seq_pais'), 'Francia'),
  (nextval('seq_pais'), 'Gabón'),
  (nextval('seq_pais'), 'Gambia'),
  (nextval('seq_pais'), 'Georgia'),
  (nextval('seq_pais'), 'Ghana'),
  (nextval('seq_pais'), 'Gibraltar'),
  (nextval('seq_pais'), 'Granada'),
  (nextval('seq_pais'), 'Grecia'),
  (nextval('seq_pais'), 'Groenlandia'),
  (nextval('seq_pais'), 'Guadalupe'),
  (nextval('seq_pais'), 'Guatemala'),
  (nextval('seq_pais'), 'Guernsey'),
  (nextval('seq_pais'), 'Guinea'),
  (nextval('seq_pais'), 'Guinea Ecuatorial'),
  (nextval('seq_pais'), 'Guinea-Bissau'),
  (nextval('seq_pais'), 'Guyana'),
  (nextval('seq_pais'), 'Haiti'),
  (nextval('seq_pais'), 'Honduras'),
  (nextval('seq_pais'), 'Hong Kong'),
  (nextval('seq_pais'), 'Hungría'),
  (nextval('seq_pais'), 'India'),
  (nextval('seq_pais'), 'Indonesia'),
  (nextval('seq_pais'), 'Irak'),
  (nextval('seq_pais'), 'Irán'),
  (nextval('seq_pais'), 'Irlanda'),
  (nextval('seq_pais'), 'Isla Pitcairn'),
  (nextval('seq_pais'), 'Islandia'),
  (nextval('seq_pais'), 'Islas Salomón'),
  (nextval('seq_pais'), 'Islas Turcas y Caicos'),
  (nextval('seq_pais'), 'Islas Virgenes Británicas'),
  (nextval('seq_pais'), 'Israel'),
  (nextval('seq_pais'), 'Italia'),
  (nextval('seq_pais'), 'Jamaica'),
  (nextval('seq_pais'), 'Japón'),
  (nextval('seq_pais'), 'Jersey'),
  (nextval('seq_pais'), 'Jordania'),
  (nextval('seq_pais'), 'Kazajstán'),
  (nextval('seq_pais'), 'Kenia'),
  (nextval('seq_pais'), 'Kirguistán'),
  (nextval('seq_pais'), 'Kiribati'),
  (nextval('seq_pais'), 'Kuwait'),
  (nextval('seq_pais'), 'Laos'),
  (nextval('seq_pais'), 'Lesotho'),
  (nextval('seq_pais'), 'Letonia'),
  (nextval('seq_pais'), 'Líbano'),
  (nextval('seq_pais'), 'Liberia'),
  (nextval('seq_pais'), 'Libia'),
  (nextval('seq_pais'), 'Liechtenstein'),
  (nextval('seq_pais'), 'Lituania'),
  (nextval('seq_pais'), 'Luxemburgo'),
  (nextval('seq_pais'), 'Macedonia'),
  (nextval('seq_pais'), 'Madagascar'),
  (nextval('seq_pais'), 'Malasia'),
  (nextval('seq_pais'), 'Malawi'),
  (nextval('seq_pais'), 'Maldivas'),
  (nextval('seq_pais'), 'Malí'),
  (nextval('seq_pais'), 'Malta'),
  (nextval('seq_pais'), 'Man, Isla de'),
  (nextval('seq_pais'), 'Marruecos'),
  (nextval('seq_pais'), 'Martinica'),
  (nextval('seq_pais'), 'Mauricio'),
  (nextval('seq_pais'), 'Mauritania'),
  (nextval('seq_pais'), 'México'),
  (nextval('seq_pais'), 'Moldavia'),
  (nextval('seq_pais'), 'Mónaco'),
  (nextval('seq_pais'), 'Mongolia'),
  (nextval('seq_pais'), 'Mozambique'),
  (nextval('seq_pais'), 'Myanmar'),
  (nextval('seq_pais'), 'Namibia'),
  (nextval('seq_pais'), 'Nauru'),
  (nextval('seq_pais'), 'Nepal'),
  (nextval('seq_pais'), 'Nicaragua'),
  (nextval('seq_pais'), 'Níger'),
  (nextval('seq_pais'), 'Nigeria'),
  (nextval('seq_pais'), 'Norfolk Island'),
  (nextval('seq_pais'), 'Noruega'),
  (nextval('seq_pais'), 'Nueva Caledonia'),
  (nextval('seq_pais'), 'Nueva Zelanda'),
  (nextval('seq_pais'), 'Omán'),
  (nextval('seq_pais'), 'Países Bajos, Holanda'),
  (nextval('seq_pais'), 'Pakistán'),
  (nextval('seq_pais'), 'Panamá'),
  (nextval('seq_pais'), 'Papúa-Nueva Guinea'),
  (nextval('seq_pais'), 'Paraguay'),
  (nextval('seq_pais'), 'Perú'),
  (nextval('seq_pais'), 'Polinesia Francesa'),
  (nextval('seq_pais'), 'Polonia'),
  (nextval('seq_pais'), 'Portugal'),
  (nextval('seq_pais'), 'Puerto Rico'),
  (nextval('seq_pais'), 'Qatar'),
  (nextval('seq_pais'), 'Reino Unido'),
  (nextval('seq_pais'), 'República Checa'),
  (nextval('seq_pais'), 'República Dominicana'),
  (nextval('seq_pais'), 'Reunión'),
  (nextval('seq_pais'), 'Ruanda'),
  (nextval('seq_pais'), 'Rumanía'),
  (nextval('seq_pais'), 'Rusia'),
  (nextval('seq_pais'), 'Sáhara Occidental'),
  (nextval('seq_pais'), 'Samoa'),
  (nextval('seq_pais'), 'San Cristobal y Nevis'),
  (nextval('seq_pais'), 'San Marino'),
  (nextval('seq_pais'), 'San Pedro y Miquelón'),
  (nextval('seq_pais'), 'San Tomé y Príncipe'),
  (nextval('seq_pais'), 'San Vincente y Granadinas'),
  (nextval('seq_pais'), 'Santa Elena'),
  (nextval('seq_pais'), 'Santa Lucía'),
  (nextval('seq_pais'), 'Senegal'),
  (nextval('seq_pais'), 'Serbia y Montenegro'),
  (nextval('seq_pais'), 'Seychelles'),
  (nextval('seq_pais'), 'Sierra Leona'),
  (nextval('seq_pais'), 'Singapur'),
  (nextval('seq_pais'), 'Siria'),
  (nextval('seq_pais'), 'Somalia'),
  (nextval('seq_pais'), 'Sri Lanka'),
  (nextval('seq_pais'), 'Sudáfrica'),
  (nextval('seq_pais'), 'Sudán'),
  (nextval('seq_pais'), 'Suecia'),
  (nextval('seq_pais'), 'Suiza'),
  (nextval('seq_pais'), 'Surinam'),
  (nextval('seq_pais'), 'Swazilandia'),
  (nextval('seq_pais'), 'Tadjikistan'),
  (nextval('seq_pais'), 'Tailandia'),
  (nextval('seq_pais'), 'Taiwan'),
  (nextval('seq_pais'), 'Tanzania'),
  (nextval('seq_pais'), 'Timor Oriental'),
  (nextval('seq_pais'), 'Togo'),
  (nextval('seq_pais'), 'Tokelau'),
  (nextval('seq_pais'), 'Tonga'),
  (nextval('seq_pais'), 'Trinidad y Tobago'),
  (nextval('seq_pais'), 'Túnez'),
  (nextval('seq_pais'), 'Turkmenistan'),
  (nextval('seq_pais'), 'Turquía'),
  (nextval('seq_pais'), 'Tuvalu'),
  (nextval('seq_pais'), 'Ucrania'),
  (nextval('seq_pais'), 'Uganda'),
  (nextval('seq_pais'), 'Uruguay'),
  (nextval('seq_pais'), 'Uzbekistán'),
  (nextval('seq_pais'), 'Vanuatu'),
  (nextval('seq_pais'), 'Venezuela'),
  (nextval('seq_pais'), 'Vietnam'),
  (nextval('seq_pais'), 'Wallis y Futuna'),
  (nextval('seq_pais'), 'Yemen'),
  (nextval('seq_pais'), 'Zambia'),
  (nextval('seq_pais'), 'Zimbabwe');
