runtime: java17
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
  - url: /.*
    script: this field is required, but ignored

#instance_class: F1 #compartida con 256 MB de memoria solo manual_scaling
instance_class: F2 #compartida con 512 MB de memoria requiere automatic_scaling

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.7
  max_concurrent_requests: 500

#manual_scaling:
#  instances: 1